### PR TITLE
fix: cmdPrefix bug

### LINKED ISSUE #34: uds run task errors when deploying bundle from `../`
### Environment

Device and OS: EC2 Instance - Amazon Linux 2
App version: v0.9.4
Kubernetes distro being used: EKS 1.27
Other:

### Steps to reproduce
This was noticed between v0.9.2 and v0.9.3 (migration to maru?)

1. Create a deploy yaml like this
```
tasks:
  - name: deploy-uds-bundle
    description: "Deploy the UDS Core Standard Bundle"
    actions:
      - cmd: "uds deploy ../uds-bundle-test-${UDS_ARCH}-${VERSION}.tar.zst --confirm --no-progress"
```
`uds run deploy-uds-bundle`

### Expected result
the uds bundle starts deploying
### Actual Result
```
 NOTE  Saving log file to /tmp/runner-2024-03-18-18-42-29-1105412261.log
     Error: unknown shorthand flag: 'b' in -bundle-test-amd64-0.0.1.tar.zst
     Usage:
       uds deploy [BUNDLE_TARBALL|OCI_REF] [flags]


     Error: unknown shorthand flag: 'b' in -bundle-test-amd64-0.0.1.tar.zst
     ERROR:  Failed to run action: command "uds deploy ../uds-bundle-test-amd64-0.0.1.tar.zst" timed out after 0
             seconds
```

seems to misinterpret `../uds` as a command or ignore it altogether?

### Additional Context

Add any other context or screenshots about the technical debt here.

### PR DESCRIPTION
**Pull request by decleaver**
## Description

Added space after cmdPrefix, otherwise the actionCmdMutation function was replacing instances where the CmdPrefix matched a relative path getting passed in. In the case of #34 the cmdPrefix was set to `./uds` which was matching and replacing the beginning of the path being passed in the cmd `uds deploy ../uds-bundle-test-${UDS_ARCH}-${VERSION}.tar.zst`. Adding a space to the cmdPrefix should prevent this from happening with any provided paths.

test will be created in uds-cli since bug was found running uds command.

## Related Issue

Fixes #34 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

### CODE REVIEW

File: src/pkg/runner/actions.go [hunk 1]
```diff
@@ -26,6 +26,24 @@ import (
 	zarfTypes "github.com/defenseunicorns/zarf/src/types"
 )
 
+// Utils is an interface that defines the GetFinalExecutablePath method.
+type Utils interface {
```
Comment (naveensrinivasan) [inline src/pkg/runner/actions.go:30]: A suggestion for the name of the interface`ExecutablePathFinder`

In `go`, it is standard to use `er` as interface `suffix` https://stackoverflow.com/questions/54213897/rule-for-golang-interface-name-and-its-number-of-methods

File: src/pkg/runner/actions.go [hunk 2]
```diff
@@ -163,7 +181,9 @@ func (r *Runner) performZarfAction(action *zarfTypes.ZarfComponentAction) error
 
 	cfg := actionGetCfg(zarfTypes.ZarfComponentActionDefaults{}, *action, r.TemplateMap)
 
-	if cmd, err = actionCmdMutation(cmd); err != nil {
+	configWrapper := Config{cmdPrefix: config.CmdPrefix}
+
+	if cmd, err = actionCmdMutation(cmd, ZarfUtils{}, configWrapper); err != nil {
```
Comment (naveensrinivasan) [inline src/pkg/runner/actions.go:186]: Another suggestion. Instead of directly creating the `ZarfUtils{}` use a `New` to return the interface

```go
func NewZarfUtils() Utils {
	return &ZarfUtils{}
}
```

File: src/pkg/runner/actions.go (hunk 1 above)
Comment (decleaver) [reply src/pkg/runner/actions.go]: addressed in latest commit

File: src/pkg/runner/actions.go (hunk 2 above)
Comment (decleaver) [reply src/pkg/runner/actions.go]: addressed in latest commit

File: src/pkg/runner/actions_test.go [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+// Package runner provides functions for running tasks in a tasks.yaml
+package runner
+
+import (
+	"fmt"
+	"testing"
+)
+
+// Mocking zarfUtils for testing purposes
+type mockZarfUtils struct{}
```
Comment (naveensrinivasan) [inline src/pkg/runner/actions_test.go:13]: 🚀 for tests!!!

**Review by UncleGedd — APPROVED** [review]
🚀
